cbs228/sameold

crates/samedec/src/app.rs
crates/sameold/src/framing.rs
crates/sameold/src/message/message.rs

- Fixes internal demo alerts to have all callsigns be 8 characters long ([NWSI 10-1712, Section A.2.11](http://www.nws.noaa.gov/directives/sym/pd01017012curr.pdf))
- Adds support for lowercase Event and Originator Codes (See Digital Alert Systems DASDEC-II and DASDEC-III use of custom alerts and messaging indorsed by FEMA and IPAWS)
- Adds support for lowercase characters as well as `().,?` in callsigns for backwards compatibility with Trilithic/Viavi, SAGE, DAS, Gorman, and TFT units. (See EAS units special characters and lowercase callsigns indorsed by FEMA and IPAWS)
These changes add small features to SAMEDEC and SAMEOLD to allow supporting more units that are indorsed by FEMA and IPAWS, as well as conforming closer to the NWS Specifications on SAME messaging.
These changes also add …

Update EAS specs to support IPAWS and EAS Vendors.

---

.github/workflows/rust_test.yml

Use the available Github Runners to automate CI testing on Linux, Windows, and macOS. Rust dependencies are cached to speed up the build.
CI binaries are not used for releases at present. For that, we would want to curate our environments very carefully—probably with containers.

github-ci: add CI tests for all major platforms

---

crates/sameold/src/framing.rs

sameold: log the full text of each SAME burst

---

Cargo.lock
crates/samedec/src/app.rs
crates/sameold/src/message/message.rs

Update to chrono 0.4.23 and replace deprecated functions.

sameold,samedec: remove deprecated chrono functions

---

Cargo.lock
crates/samedec/Cargo.toml
crates/samedec/src/app.rs
crates/samedec/src/cli.rs
crates/samedec/src/main.rs

Improve error reporting for common mistakes, such as specifying a non-existent file or for trying to use standard input via a pty.
Update to clap 4.1 which offers better macros and an improved `--help` output.
The input arguments themselves are unchanged.

samedec: CLI Improvements

---

.gitattributes
.github/workflows/rust_release.yml
.github/workflows/rust_test.yml
.gitignore
Dockerfile

Instead of downloading sources once per job, or trying to keep cargo caches for them separately, use *one* dependency cache that is generated with `cargo vendor`. The vendored sources are platform-independent and support all targets and all features.
This is a substantial speed boost for our Docker Actions on non-x86_64 platforms, and it is also a workaround for docker/build-push-action#621.

Use `cargo-vendor` in CI runs

---

.github/workflows/rust_release.yml
Cargo.lock
crates/samedec/Cargo.toml
crates/samedec/src/main.rs
crates/sameold/Cargo.toml
crates/sameold/README.md

Upgrade `Cargo.lock` packages to best-available versions.
* Adopt an MSRV policy for our library, `sameold`
* Replace `atty` with `is-terminal`

Dependency updates

---

Cargo.lock
Cargo.toml
crates/samedec/Cargo.toml
crates/samedec/src/main.rs

Update dependencies for `samedec`. The number of duplicate dependencies that differ only by version number is substantially reduced.
Minor code changes are made to replace `is-terminal` with `terminal_size`.

Dependency update

---

.github/workflows/rust_release.yml

Update the release CI to use the latest versions of qemu, buildx, and docker.

ci: update docker action versions

---

crates/samedec/src/app.rs
crates/samedec/src/main.rs

Previously, `samedec::app::run()` would unceremoniously exit on EOF. Since an EOF results in samples being "stranded" in filter buffers and other parts of the system, it is necessary to push zeros through the system to make it output any remaining Messages.
This "flush" operation was performed by isolated code that ran after the app terminated. This would print the Message(s), but it would not take any other actions like spawning child processes.
We should spawn the child even if there's no audio data that follows. The state machine will simply `wait()` for it to terminate and then exit.
This change permits us to run child processes on short snippets of SAME data—i.e., our `sample/*.bin` data files.
This is CLI-expanding behavior.

samedec: flush on EOF in main app

---

crates/samedec/README.md
crates/sameold/src/message/significance.rs

The `SignificanceLevel::Message` is not part of NWSI 10-1712 or any other known standard, and very few event codes in sameold ever implement it.
Discontinue this enum variant.
The following event codes are affected and are upgraded to `Statement`s:
* ADR Administrative Message
* NMN Network Message Notification
This is an API-BREAKING change. The samedec CLI is unaffected, but it is removed from the documentation.

sameold,samedec: drop SignificanceLevel::Message

---

Cargo.lock
crates/sameold/Cargo.toml
crates/sameold/src/message/significance.rs

Thanks to changes in strum, we can no longer implement our own `From<&str>` to choose what happens when the input is unmatched. In order to keep the API, we must drop the `EnumString` derive macro on `SignificanceLevel` and implement the parser ourselves.
Add `EnumIter` for use in unit tests.

sameold: update to strum 0.26

---

crates/sameold/README.md
crates/sameold/src/lib.rs
crates/sameold/src/receiver.rs
crates/sameold/src/receiver/output.rs

Rename the `SameEvent` to `SameReceiverEvent`. The `SameReceiver` uses this type to communicate modem status changes, such as the acquisition and/or loss of carrier. The old name was somewhat ambiguous with `EventCode`, and the rename helps disambiguate them.
This is an API-BREAKING change.

sameold: rename SameEvent → SameReceiverEvent

---

Cargo.lock
crates/sameold/Cargo.toml

Discontinues use of a yanked version of bytemuck.
All dependencies are updated to the latest-available version for the current MSRV.

sameold: update dependencies

---

.github/workflows/rust_release.yml

The Github Actions runners are aarch64, so that is what we will use going forward. Fixes release job failure.

ci: migrate MacOS builds to aarch64-apple-darwin

---

.github/container/Dockerfile.base
.github/container/Dockerfile.rust.aarch64-unknown-linux-gnu
.github/container/Dockerfile.rust.armv7-unknown-linux-gnueabihf
.github/container/Dockerfile.rust.i686-unknown-linux-gnu
.github/container/Dockerfile.rust.x86_64-unknown-linux-gnu
.github/container/build.sh
.github/container/rootfiles/usr/local/bin/qemu-run-maybe
.github/workflows/rust_release.yml
.github/workflows/rust_test.yml
Dockerfile
sample/test.sh

Add more CI checks for:
* Git whitespace errors
* cargo-fmt compliance
* cargo check output (warns only)
We also migrate the Linux release jobs to a container image,
ghcr.io/cbs228/sameold/builder/${TARGET}
which has a build script and Dockerfiles available. The image relies on Debian's excellent multiarch and cross-compiler support to build for non-amd64 Debian architectures, including:
* armhf
* arm64
* i386
Previously, support for these architectures relied on running an entire foreign-architecture container, with a foreign-architecture Rust toolchain, in qemu. This was—predictably—both slow and unreliable. Build jobs usually timed out. Cross-compiling is much faster.
musl releases are discontinued for the time being. Our gnu builds continue to target glibc 2.28.
The `./test.sh` …

ci: containerize the environment, more checks

---

crates/sameold/src/receiver/demod.rs

Ignore a dead code lint for `Demod::push()`. This method is used within unit tests, and I want to keep it.

sameold: permit dead code for Demod::push()

---

.github/container/Dockerfile.base
.github/container/Dockerfile.rust
.github/container/Dockerfile.rust.aarch64-unknown-linux-gnu
.github/container/Dockerfile.rust.armv7-unknown-linux-gnueabihf
.github/container/Dockerfile.rust.i686-unknown-linux-gnu
.github/container/Dockerfile.rust.x86_64-unknown-linux-gnu
.github/container/README.md
.github/container/build.sh

* Improve UX when building locally / not on CI:
* Make in-image `/install` and cargo home directory world-writeable, which helps with permssions issues. Unlike the official rust docker image, we still don't make the rustup and rust toolchain directories world-writeable. Build systems have no business messing with that.
* Discontinue `/target` target directory. Use the standard cargo target directory of `./target` instead. If the user wants a separate target directory, they can bind-mount one.
* Make `build.sh` easier to read and potentially usable with Docker. Omit the `podman login` step.
* Add README for the images.

ci: container image improvements

---

.github/workflows/rust_release.yml
.github/workflows/rust_test.yml
README.md

In [1], we migrated macos builds from x86_64 to aarch64. There are still plenty of x86_64 macs running around, and our CI binaries should support them if we can. Ensure we cross-compile for x86_64 as well.
[1]: 46a0222026abdc922fc1480f9ea103cac65d0300

ci: restore apple x86_64 target

---

Cargo.lock
crates/samedec/Cargo.toml
crates/samedec/src/main.rs
crates/sameold/Cargo.toml
crates/sameold/src/receiver/codesquelch.rs
crates/sameold/src/receiver/symsync.rs

Update **MSRV** to:
* `sameold`: 1.70
* `samedec`: 1.74
so we can take advantage of the latest versions of our dependencies, including clap 4.5.
Minor refactors are required for:
* `terminal_size`: replace deprecated function
* `arraydeque`: template changes

Update MSRV and dependencies

---

.github/workflows/workflow.yml

Ensure that all PRs pass `cargo check` and `cargo doc` builds before they are gated into the full build matrix.
In addition, we add GHA annotations to improve error messages.

ci: add cargo check and cargo doc checks

---

crates/sameold/Cargo.toml

`assert_approx_eq` provides macros for unit tests. This dependency should not propagate to other workspace crates. Make it a dev-dependency instead.

sameold: make assert_approx_eq a dev-dependency

---

.github/container/rust/Dockerfile
.github/container/rust/rootfiles/usr/local/bin/qemu-run-maybe
.github/workflows/workflow.yml

Use our homegrown container image for running the initial "check and vendor" job. All Linux jobs now run containerized.
In addition:
* Add cargo-fmt to containers
* Run i686 binaries on x86_64 without emulation

ci: use container image for "check and vendor" job

---

Cargo.lock
crates/sameold/Cargo.toml
crates/sameold/src/receiver/dcblock.rs
crates/sameold/src/receiver/demod.rs
crates/sameold/src/receiver/equalize.rs
crates/sameold/src/receiver/filter.rs

`SliceRingBuffer` is unsound and has multiple security advisories [1] [2]. There has been no apparent progress on fixes since May 2025 [3]. The crate's large volume of interdependent `unsafe` blocks will likely make it very tricky to maintain.
`SliceRingBuffer` backs the FIR filter `Window`. The slice coercion is used to align the back of the `Window` (with the most recent samples) with the FIR filter taps. We don't actually *need* a slice for this: we can get by with a `DoubleEndedIterator` instead.
* Make `Window` convertible to an iterator of numbers, via `IntoIterator`. Replace all uses of slices with iterators.
* Store FIR `FilterCoeff` taps in "proper" order, instead of reversed. Since we use iterators instead of slices, reverse-order is no longer convenient.
* Replace …

sameold: drop slice-ring-buffer

---

crates/samedec/src/spawner.rs
crates/sameplace/src/message.rs
sample/npt.22050.s16le.sh
sample/two_and_two.22050.s16le.sh

Previous versions of sameplace erroneously stated that the expiration time of a SAME message was
issue datetime + purge duration
This is *almost* correct, but there's a catch:
* the expiration time is rounded to the nearest 15 minute increment for durations ≤1 hour
* the expiration time is rounded to the nearest 30 minute increment for longer-duration messages
* the maximum duration of a SAME message is 99.5 hours [1]
Add `MessageHeader::purge_datetime()` to calculate this time, and fix the incorrect `Message::is_expired_at()` implementation to match. Documentation is given a touch-up.
This is an API-expanding change for sameold and will change samedec's `SAMEDEC_PURGETIME` values.
[1]: https://www.weather.gov/nwr/samealertduration

sameold,samedec: round purge times to 15 or 30 minutes

---

.github/workflows/workflow.yml

Previously, "build and test" jobs would upload releases themselves, if they were cleared to do so. This mixing is not great from a pipeline security standpoint since the entire workflow runs with `contents: write`. It also introduces the potential for a *partial release*. If some jobs complete, but others do not, then a release will be issued without all its binaries.
Make this operation more atomic by performing publishing activities in separate jobs. The publish jobs download all the artifacts and create the release.

ci: make releases atomic
